# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
