# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20170811_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto2',
            field=models.FileField(blank=True, null=True, upload_to='img/config/equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='foto3',
            field=models.FileField(blank=True, null=True, upload_to='img/config/equipo'),
        ),
    ]
