# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20170827_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad_UMB', models.CharField(choices=[('TON', 'Toneladas'), ('L', 'Litros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('LB', 'Libras')], max_length=5)),
                ('concentracion', models.CharField(blank=True, max_length=50, null=True)),
                ('N_de_lote_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('cuarentena', 'Cuarentena'), ('rechazado', 'Rechazado')], max_length=30, null=True)),
                ('ficha_tecnica', models.FileField(upload_to='pdf/config/material/certificado_calidad')),
                ('costo_UMB', models.CharField(max_length=150)),
            ],
        ),
    ]
