# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fecha_de_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
