# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_material_fecha_de_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricante',
            old_name='Nombre_fabricante',
            new_name='nombre_fabricante',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='Nombre_proveedor',
            new_name='nombre_proveedor',
        ),
    ]
