# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_material_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Proveedor',
            new_name='proveedor',
        ),
        migrations.AddField(
            model_name='material',
            name='fabricante',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='config.Fabricante'),
        ),
    ]
