# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20170827_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='material',
            name='fabricante',
            field=models.ManyToManyField(to='config.Fabricante'),
        ),
    ]
