# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_auto_20170827_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('apariencia', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=50)),
                ('olor', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('volumen', models.CharField(max_length=50)),
                ('grado_alcoholico', models.CharField(max_length=50)),
                ('mesofilos_aerobios_totales', models.CharField(max_length=50)),
                ('pseudomonas_aeruginosa', models.CharField(max_length=50)),
                ('coliformes_totales', models.CharField(max_length=50)),
                ('Staphylococus_aureus', models.CharField(max_length=50)),
                ('materia_prima', models.ManyToManyField(to='config.Material')),
            ],
        ),
    ]
