# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_auto_20170906_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='certificado_calidad',
        ),
        migrations.AlterField(
            model_name='material',
            name='ficha_tecnica',
            field=models.FileField(upload_to='pdf/config/material/certificado_calidad'),
        ),
    ]
