# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171010_0841'),
        ('config', '0014_auto_20171009_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Empresa'),
        ),
    ]
