# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_auto_20171010_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ficha_tecnica',
            field=models.FileField(blank=True, upload_to='pdf/config/equipo'),
        ),
    ]
