# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('fabricante', models.CharField(default='no aplica', max_length=50)),
                ('capacidad_minima_de_operacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacidad_maxima_de_operacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad', models.CharField(choices=[('TON', 'Toneladas'), ('L', 'Litros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('LB', 'Libras')], max_length=5)),
                ('ficha_tecnica', models.FileField(blank=True, upload_to='pdf/config/equipo')),
                ('fecha_calibracion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('M', 'En mantenimiento'), ('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True)),
                ('foto1', models.FileField(blank=True, null=True, upload_to='img/config/equipo')),
                ('foto2', models.FileField(blank=True, null=True, upload_to='img/config/equipo')),
                ('foto3', models.FileField(blank=True, null=True, upload_to='img/config/equipo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fabricante', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad_UMB', models.CharField(choices=[('TON', 'Toneladas'), ('L', 'Litros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('LB', 'Libras')], max_length=5)),
                ('ficha_tecnica', models.FileField(blank=True, upload_to='pdf/config/material/ficha_tecnica')),
                ('concentracion', models.CharField(blank=True, max_length=50, null=True)),
                ('N_de_lote_fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_de_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('aprobado', 'Aprobado'), ('cuarentena', 'Cuarentena'), ('rechazado', 'Rechazado')], max_length=30, null=True)),
                ('certificado_calidad', models.FileField(blank=True, null=True, upload_to='pdf/config/material/certificado_calidad')),
                ('costo_UMB', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
                ('fabricante', models.ManyToManyField(to='config.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('presentacion', models.CharField(max_length=50)),
                ('apariencia', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=50)),
                ('olor', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('volumen', models.CharField(max_length=50)),
                ('grado_alcoholico', models.CharField(max_length=50)),
                ('mesofilos_aerobios_totales', models.CharField(max_length=50)),
                ('pseudomonas_aeruginosa', models.CharField(max_length=50)),
                ('coliformes_totales', models.CharField(max_length=50)),
                ('Staphylococus_aureus', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
                ('materia_prima', models.ManyToManyField(to='config.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.ManyToManyField(to='config.Proveedor'),
        ),
    ]
