# Generated by Django 2.0.1 on 2018-01-24 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20180124_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('fabricante', models.CharField(max_length=50)),
                ('capacidad_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacidad_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unidad', models.CharField(choices=[('TON', 'Toneladas'), ('L', 'Litros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('LB', 'Libras')], max_length=20)),
                ('fecha_calibracion', models.DateField(blank=True, null=True)),
                ('calibrable', models.BooleanField()),
                ('CALIFICADO', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('NA', 'NO APLICA')], max_length=15)),
                ('estado', models.CharField(choices=[('MANTENIMIENTO', 'En mantenimiento'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=20)),
                ('otras_caracteristicas', models.TextField(blank=True, null=True)),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='pdf/config/equipo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
    ]
