# Generated by Django 2.0.1 on 2018-02-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180124_0359'),
        ('config', '0002_auto_20180124_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fabricante', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MATERIA_PRIMA', 'materia prima'), ('MATERIAL_EMPAQUE', 'material de empaque')], max_length=30)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('unidad', models.CharField(choices=[('TON', 'Toneladas'), ('L', 'Litros'), ('KG', 'Kilogramos'), ('G', 'Gramos'), ('LB', 'Libras'), ('ADIMENSIONAL', 'adimensional')], max_length=20)),
                ('pureza_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pureza_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ficha_seguridad', models.FileField(blank=True, upload_to='pdf/config/material/ficha_seguridad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Empresa')),
            ],
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Fabricante'),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.ManyToManyField(to='config.Proveedor'),
        ),
    ]
