# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'administrador'), ('L', 'Limitado')], max_length=20),
        ),
    ]
