# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171009_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
